#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         4
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config shadowless_monocle	 true
bspc config focus_follows_pointer true
bspc config presel_feedback color \#d5c4a1
bpsc config normal_border_color   \#3c3836
bpsc config focused_border_color  \#d5c4a1

bspc rule -a Firefox desktop=^2
bpsc rule -a Spotify desktop=^4

~/.config/bspwm/monitors.sh
~/.fehbg &
picom & 
~/.config/polybar/forest/launch.sh
setxkbmap br
dunst
/usr/lib/xfce-polkit/xfce-polkit
~/pcloud
xsetroot -cursor_name "WhiteSur Cursors" & 
